#!/bin/bash

sudo apt remove -y fonts-crosextra-caladea, fonts-crosextra-carlito
sudo apt remove -y fonts-dejavu-core, fonts-dejavu-extra
sudo apt remove -y fonts-ebgaramond, fonts-ebgaramond-extra
sudo apt remove -y fonts-font-awesome, fonts-ebgaramond-extra
sudo apt remove -y fonts-noto-mono, fonts-noto-core, fonts-noto-color-emoji
sudo apt remove -y fonts-samyak-taml, fonts-samyak-mlym, fonts-samyak-gujr
sudo apt remove -y fonts-smc-manjari, fonts-smc-gayathri, fonts-smc-chilanka
sudo apt remove -y fonts-smc-uroob, fonts-smc-suruma, fonts-smc-raghumalayalamsans, fonts-smc-rachana, fonts-smc-meera, fonts-smc-keraleeyam, fonts-smc-karumbi, fonts-smc-dyuthi, fonts-smc-anjalioldlipi
sudo apt remove -y fonts-telu-extra, fonts-smc-uroob, fonts-smc-suruma, fonts-smc-raghumalayalamsans, fonts-smc-rachana, fonts-smc-meera, fonts-smc-manjari, fonts-smc-keraleeyam, fonts-smc-karumbi, fonts-smc-dyuthi, fonts-smc-chilanka, fonts-smc-anjalioldlipi, fonts-pagul, fonts-orya-extra, fonts-lohit-telu, fonts-lohit-taml, fonts-lohit-taml-classical, fonts-lohit-orya, fonts-lohit-mlym, fonts-lohit-knda, fonts-lohit-guru, fonts-lohit-gujr, fonts-lohit-deva, fonts-lohit-beng-bengali, fonts-lohit-beng-assamese, fonts-guru-extra, fonts-gujr-extra, fonts-gubbi, fonts-droid-fallback, fonts-deva-extra, fonts-dejavu-core, fonts-beng-extra, fontconfig-config, fonts-noto-mono, fonts-noto-core, fonts-crosextra-carlito, fonts-texgyre, language-selector-common, fonts-lmodern
sudo apt remove -y fonts-tlwg-waree-ttf, fonts-tlwg-umpush-ttf, fonts-tlwg-typo-ttf, fonts-tlwg-typist-ttf, fonts-tlwg-typewriter-ttf, fonts-tlwg-sawasdee-ttf, fonts-tlwg-purisa-ttf, fonts-tlwg-norasi-ttf, fonts-tlwg-mono-ttf, fonts-tlwg-loma-ttf, fonts-tlwg-laksaman-ttf, fonts-tlwg-kinnari-ttf, fonts-tlwg-garuda-ttf
sudo apt remove -y fonts-urw-base35, fonts-smc-manjari, fonts-smc-gayathri, fonts-smc-chilanka, fonts-noto-cjk, fonts-mathjax, fonts-inter, fonts-ebgaramond, fonts-cabin, fonts-freefont-otf, fonts-font-awesome, fonts-cantarell, fonts-stix, fonts-lobster, fonts-linuxlibertine, fonts-ebgaramond-extra, fonts-sil-gentiumplus-compact, fonts-lobstertwo, fonts-b612
sudo apt remove -y fonts-urw-base35, fonts-tlwg-waree, fonts-tlwg-umpush, fonts-tlwg-typo, fonts-tlwg-typist, fonts-tlwg-norasi, fonts-tlwg-mono, fonts-tlwg-loma, fonts-tlwg-laksaman, fonts-tlwg-kinnari, fonts-tlwg-garuda, fonts-telu-extra, fonts-smc-uroob, fonts-smc-suruma, fonts-smc-raghumalayalamsans, fonts-smc-rachana, fonts-smc-meera, fonts-smc-manjari, fonts-smc-keraleeyam, fonts-smc-karumbi, fonts-smc-dyuthi, fonts-smc-chilanka, fonts-smc-anjalioldlipi, fonts-pagul, fonts-orya-extra, fonts-noto-cjk, fonts-lohit-telu, fonts-lohit-taml, fonts-lohit-taml-classical, fonts-lohit-orya, fonts-lohit-knda, fonts-lohit-guru, fonts-lohit-gujr, fonts-lohit-deva, fonts-lohit-beng-bengali, fonts-lohit-beng-assamese, fonts-khmeros-core, fonts-guru-extra, fonts-gujr-extra, fonts-gubbi, fonts-droid-fallback, fonts-deva-extra, fonts-dejavu-core, fonts-beng-extra, fontconfig-config, fonts-crosextra-carlito, fonts-linuxlibertine, fonts-opensymbol, fonts-texgyre, language-selector-common, fonts-lmodern
sudo apt remove -y fonts-urw-base35, fonts-tlwg-waree, fonts-tlwg-umpush, fonts-tlwg-typo, fonts-tlwg-typist, fonts-tlwg-norasi, fonts-tlwg-mono, fonts-tlwg-loma, fonts-tlwg-laksaman, fonts-tlwg-kinnari, fonts-tlwg-garuda, fonts-telu-extra, fonts-smc-uroob, fonts-smc-suruma, fonts-smc-raghumalayalamsans, fonts-smc-rachana, fonts-smc-meera, fonts-smc-manjari, fonts-smc-keraleeyam, fonts-smc-karumbi, fonts-smc-dyuthi, fonts-smc-chilanka, fonts-smc-anjalioldlipi, fonts-pagul, fonts-orya-extra, fonts-noto-cjk, fonts-lohit-telu, fonts-lohit-taml, fonts-lohit-taml-classical, fonts-lohit-orya, fonts-lohit-mlym, fonts-lohit-knda, fonts-lohit-guru, fonts-lohit-gujr, fonts-lohit-deva, fonts-lohit-beng-bengali, fonts-lohit-beng-assamese, fonts-khmeros-core, fonts-guru-extra, fonts-gujr-extra, fonts-gubbi, fonts-droid-fallback, fonts-deva-extra, fonts-dejavu-core, fonts-beng-extra, fontconfig-config, fonts-noto-mono, fonts-noto-core, fonts-crosextra-carlito, fonts-linuxlibertine, fonts-opensymbol, fonts-texgyre, language-selector-common, fonts-lmodern
sudo apt remove -y fonts-yrsa-rasa, fonts-ubuntu, fonts-tlwg-waree-ttf, fonts-tlwg-umpush-ttf, fonts-tlwg-typo-ttf, fonts-tlwg-typist-ttf, fonts-tlwg-typewriter-ttf, fonts-tlwg-sawasdee-ttf, fonts-tlwg-purisa-ttf, fonts-tlwg-norasi-ttf, fonts-tlwg-mono-ttf, fonts-tlwg-loma-ttf, fonts-tlwg-laksaman-ttf, fonts-tlwg-kinnari-ttf, fonts-tlwg-garuda-ttf, fonts-tibetan-machine, fonts-telu-extra, fonts-smc-uroob, fonts-smc-suruma, fonts-smc-raghumalayalamsans, fonts-smc-rachana, fonts-smc-meera, fonts-smc-keraleeyam, fonts-smc-karumbi, fonts-smc-dyuthi, fonts-smc-anjalioldlipi, fonts-sil-padauk, fonts-sil-abyssinica, fonts-sarai, fonts-samyak-taml, fonts-samyak-mlym, fonts-samyak-gujr, fonts-samyak-deva, fonts-sahadeva, fonts-pagul, fonts-orya-extra, fonts-navilu, fonts-nakula, fonts-lohit-telu, fonts-lohit-taml, fonts-lohit-taml-classical, fonts-lohit-orya, fonts-lohit-mlym, fonts-lohit-knda, fonts-lohit-guru, fonts-lohit-gujr, fonts-lohit-deva, fonts-lohit-beng-bengali, fonts-lohit-beng-assamese, fonts-lklug-sinhala, fonts-liberation2, fonts-liberation, fonts-lao, fonts-khmeros-core, fonts-kalapi, fonts-kacst, fonts-kacst-one, fonts-guru-extra, fonts-gujr-extra, fonts-gubbi, fonts-gargi, fonts-freefont-ttf, fonts-droid-fallback, fonts-deva-extra, fonts-dejavu-core, fonts-beng-extra, ttf-bitstream-vera, fonts-roboto-unhinted, fonts-gfs-complutum, fonts-crosextra-caladea, fonts-croscore, fonts-comfortaa, fonts-adf-accanthis, fonts-oflb-asana-math, fonts-junicode, fonts-gfs-solomos, fonts-gfs-olga, fonts-gfs-neohellenic, fonts-gfs-didot, fonts-lato, fonts-noto-mono, fonts-noto-core, fonts-gfs-artemisia, fonts-font-awesome, fonts-crosextra-carlito, fonts-adf-gillius, fonts-adf-berenis, fonts-ebgaramond-extra, fonts-adf-universalis, fonts-opensymbol, fonts-noto-color-emoji, fonts-sil-gentiumplus, fonts-sil-gentium-basic, fonts-sil-gentium, fonts-open-sans, fonts-dejavu-extra, fonts-lyx
sudo apt purge -y && sudo apt autoremove -y

